{% set name = "robot_descriptions" %}
{% set version = "1.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/robot_descriptions-{{ version }}.tar.gz
  sha256: 20bca385bdd101e17da68976734c2fbd5631caf470315de133cac82bf38c54dd

build:
  entry_points:
    - robot_descriptions = robot_descriptions.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit
    - pip
  run:
    - python >={{ python_min }}
    - gitpython >=3.1.18
    - tqdm >=4.64.0

test:
  imports:
    - robot_descriptions
  commands:
    - pip check
    - robot_descriptions --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/robot-descriptions/robot_descriptions.py
  summary: Import open source robot description as Python modules.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - GiulioRomualdi
    - stephane-caron
